"""Set source positions on the closed ASTs generated by fpstreams."""

from __future__ import annotations

import ast
from typing import Any, TypeVar

_AstT = TypeVar("_AstT", bound=ast.AST)


def locate_generated_ast(tree: _AstT) -> _AstT:
    """Locate fresh generated nodes at line 1 in their original traversal order.

    These trees contain no parsed source or existing positions to preserve. This
    helper is not a replacement for ``fix_missing_locations`` on arbitrary ASTs.
    """
    node: Any = tree
    if "lineno" in node._attributes:
        node.lineno = node.end_lineno = 1
        node.col_offset = node.end_col_offset = 0
    for field in node._fields:
        value = getattr(node, field, None)
        if isinstance(value, ast.AST):
            locate_generated_ast(value)
        elif isinstance(value, list):
            for child in value:
                if isinstance(child, ast.AST):
                    locate_generated_ast(child)
    return tree
